name: Build, test and snapshot image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build/Test
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: hugespaceship
          POSTGRES_USER: hugespaceship
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: Update Dependencies
      run: go mod download
      
    - name: Build 
      run: go build -v ./...
      env:
        HS_DB_HOST: postgres

    - name: Test
      run: go test ./...
      env:
        HS_DB_HOST: postgres

  docker:
    name: Build container and push to registry
    if: github.ref == 'refs/heads/main'
    needs:
    - build
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          target: hugespaceship
          provenance: true
          tags: ghcr.io/hugespaceship/hugespaceship:nightly
          cache-from: type=gha
          cache-to: type=gha,mode=max

